on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.18.1
          registry-url: https://registry.npmjs.org/
      - run: git config --global user.email "release-bot@groww.in"
      - run: git config --global user.name "github-bot"
      - run: npm install
      - run: npm run build
      - run: npm publish --access public --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: npm run pushTags
        env:
          github-token: ${{secrets.GITHUB_TOKEN}}
